<?php
/**
 * Asset enqueue — frontend + editor.
 *
 * Versioning comes from `*.asset.php` files generated by @wordpress/scripts
 * so that busting happens on every build without manual bumps.
 *
 * @package ProgerBlog
 */

declare(strict_types=1);

namespace ProgerBlog\Assets;

/**
 * Read `build/<handle>.asset.php` to derive version and dependencies.
 */
function read_asset(string $handle): array {
	$file = PROGER_BLOG_PATH . 'build/' . $handle . '.asset.php';
	if (! file_exists($file)) {
		return ['dependencies' => [], 'version' => PROGER_BLOG_VERSION];
	}
	$asset = require $file;
	return [
		'dependencies' => map_module_deps($asset['dependencies'] ?? []),
		'version'      => $asset['version'] ?? PROGER_BLOG_VERSION,
	];
}

/**
 * Normalise classic-script IDs emitted by DependencyExtractionWebpackPlugin
 * (e.g. `wp-interactivity`) into Script Modules API IDs (`@wordpress/interactivity`).
 *
 * @param array<int, string> $deps
 * @return array<int, string>
 */
function map_module_deps(array $deps): array {
	$mapped = array_map(
		static function (string $dep): string {
			return str_starts_with($dep, 'wp-') ? '@wordpress/' . substr($dep, 3) : $dep;
		},
		$deps
	);
	return array_values(array_unique($mapped));
}

add_action('wp_enqueue_scripts', static function (): void {
	$style = read_asset('main');
	wp_enqueue_style(
		'proger-blog-main',
		PROGER_BLOG_URI . 'build/main.css',
		[],
		$style['version']
	);

	wp_enqueue_style(
		'proger-blog-fonts',
		'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500;700&display=swap',
		[],
		null
	);

	wp_enqueue_style(
		'proger-blog-icons',
		'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&display=block',
		[],
		null
	);
});

add_action('wp_enqueue_scripts', static function (): void {
	$nav = read_asset('interactivity-nav');
	wp_register_script_module(
		'proger-blog/nav',
		PROGER_BLOG_URI . 'build/interactivity-nav.js',
		$nav['dependencies'],
		$nav['version']
	);
	wp_enqueue_script_module('proger-blog/nav');
}, 20);

add_action('enqueue_block_editor_assets', static function (): void {
	$editor = read_asset('main');
	wp_enqueue_style(
		'proger-blog-editor',
		PROGER_BLOG_URI . 'build/main.css',
		[],
		$editor['version']
	);
});

add_filter('autoptimize_filter_js_exclude', static function (string $exclude): string {
	return $exclude . ', /proger-blog/, /blocks/code/view.js, /blocks/toc/view.js, /interactivity-nav.js';
});
