#!/usr/bin/env node
/**
 * Sync design tokens from src/tokens/design-tokens.json into:
 *   - theme.json                             (WordPress Site Editor palette + spacing)
 *   - src/styles/tokens-root.css             (:root custom properties — kept for
 *                                             block SCSS that still references
 *                                             var(--proger-color-*))
 *
 * Tailwind is configured to consume design-tokens.json directly via require()
 * in tailwind.config.js, so we no longer emit a separate Tailwind/SCSS map.
 *
 * Usage: node scripts/sync-tokens.mjs [--check]
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const themeRoot = path.resolve(__dirname, '..');

const tokensPath = path.join(themeRoot, 'src/tokens/design-tokens.json');
const themeJsonPath = path.join(themeRoot, 'theme.json');
const rootCssPath = path.join(themeRoot, 'src/styles/tokens-root.css');

const tokens = JSON.parse(fs.readFileSync(tokensPath, 'utf8'));

const slugify = (s) => s.replace(/[^a-z0-9-]/gi, '-').toLowerCase();
const toKebab = (s) => s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

function buildThemeJson() {
	const palette = Object.entries(tokens.color).map(([name, color]) => ({
		slug: slugify(name),
		name: name.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
		color,
	}));

	const fontSizes = Object.entries(tokens.typography.fontSizes).map(([slug, size]) => ({
		slug,
		name: slug.toUpperCase(),
		size,
	}));

	const spacingSizes = Object.entries(tokens.spacing).map(([slug, size]) => ({
		slug,
		name: `${slug}px`,
		size,
	}));

	return {
		$schema: 'https://schemas.wp.org/trunk/theme.json',
		version: 3,
		settings: {
			appearanceTools: true,
			useRootPaddingAwareAlignments: true,
			layout: { contentSize: tokens.layout.contentMax, wideSize: '1100px' },
			color: { palette, defaultPalette: false, defaultGradients: false, customDuotone: false, gradients: [] },
			typography: {
				fontFamilies: [
					{ slug: 'body', name: 'Body (Inter)', fontFamily: tokens.typography.fontFamilies.body },
					{ slug: 'headline', name: 'Headline (Inter)', fontFamily: tokens.typography.fontFamilies.headline },
					{ slug: 'mono', name: 'Mono (JetBrains Mono)', fontFamily: tokens.typography.fontFamilies.mono },
				],
				fontSizes,
				defaultFontSizes: false,
				fluid: true,
				lineHeight: true,
				letterSpacing: true,
				fontStyle: true,
				fontWeight: true,
			},
			spacing: {
				units: ['px', 'em', 'rem', '%', 'vh', 'vw'],
				spacingSizes,
				defaultSpacingSizes: false,
				padding: true,
				margin: true,
				blockGap: true,
			},
			border: { color: true, radius: true, style: true, width: true },
		},
		styles: {
			color: {
				background: 'var(--wp--preset--color--background)',
				text: 'var(--wp--preset--color--on-background)',
			},
			typography: {
				fontFamily: 'var(--wp--preset--font-family--body)',
				fontSize: tokens.typography.fontSizes.md,
				lineHeight: tokens.typography.lineHeights.normal,
			},
		},
	};
}

function buildRootCss() {
	const lines = [];
	lines.push('/* Auto-generated by scripts/sync-tokens.mjs. DO NOT EDIT BY HAND. */');
	lines.push('/* Minimal :root custom properties for runtime CSS that cannot be expressed via Tailwind. */');
	lines.push(':root {');
	for (const [name, value] of Object.entries(tokens.color)) {
		lines.push(`\t--proger-color-${name}: ${value};`);
	}
	for (const [key, value] of Object.entries(tokens.motion)) {
		lines.push(`\t--proger-${toKebab(key)}: ${value};`);
	}
	lines.push('}');
	lines.push('');
	return lines.join('\n');
}

const checkMode = process.argv.includes('--check');
const diffs = [];

function writeFile(filePath, content) {
	const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';
	if (existing === content) return false;
	if (checkMode) { diffs.push(filePath); return false; }
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, content);
	return true;
}

const themeJson = JSON.stringify(buildThemeJson(), null, '\t') + '\n';
const rootCss = buildRootCss();

const wroteTheme = writeFile(themeJsonPath, themeJson);
const wroteCss = writeFile(rootCssPath, rootCss);

// Remove legacy generated files if present.
for (const legacy of ['src/styles/_tokens.scss', 'src/styles/_tokens.css']) {
	const p = path.join(themeRoot, legacy);
	if (fs.existsSync(p)) {
		if (checkMode) diffs.push(p);
		else fs.unlinkSync(p);
	}
}

if (checkMode) {
	if (diffs.length) {
		console.error('Token drift detected in:');
		diffs.forEach((f) => console.error('  - ' + path.relative(themeRoot, f)));
		process.exit(1);
	}
	console.log('Tokens are in sync.');
	process.exit(0);
}

const summary = [];
if (wroteTheme) summary.push('theme.json');
if (wroteCss) summary.push('src/styles/tokens-root.css');
console.log(summary.length ? 'Updated: ' + summary.join(', ') : 'Tokens already in sync.');
