/* Auto-generated by scripts/sync-tokens.mjs. DO NOT EDIT BY HAND. */
/* Source: src/tokens/design-tokens.json */
const tokens = require('./src/tokens/design-tokens.json');

/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: 'class',
	content: [
		'./templates/**/*.html',
		'./parts/**/*.html',
		'./patterns/**/*.php',
		'./src/**/*.{js,jsx,ts,tsx}',
		'./inc/**/*.php',
		'./functions.php',
		'./*.php',
	],
	theme: {
		extend: {
			colors: tokens.color,
			fontFamily: {
				headline: ['Inter', 'system-ui', 'sans-serif'],
				body: ['Inter', 'system-ui', 'sans-serif'],
				mono: ['"JetBrains Mono"', '"Fira Code"', 'Consolas', 'monospace'],
			},
			borderRadius: {
				DEFAULT: '0.25rem',
				sm: tokens.radius.sm,
				md: tokens.radius.md,
				lg: tokens.radius.lg,
				xl: tokens.radius.xl,
				'2xl': '1.5rem',
				full: tokens.radius.full,
			},
			boxShadow: {
				ambient: tokens.shadow.ambient,
				sm: tokens.shadow.sm,
				md: tokens.shadow.md,
				lg: tokens.shadow.lg,
			},
			screens: {
				sm: tokens.breakpoints.sm,
				md: tokens.breakpoints.md,
				lg: tokens.breakpoints.lg,
				xl: tokens.breakpoints.xl,
				'2xl': '1536px',
			},
			transitionTimingFunction: {
				standard: tokens.motion.easingStandard,
			},
			transitionDuration: {
				fast: tokens.motion.durationFast,
				base: tokens.motion.durationBase,
			},
			fontSize: {
				'display-lg': [tokens.typography.fontSizes['display-lg'], { lineHeight: '1.05', letterSpacing: '-0.02em' }],
				'display-md': [tokens.typography.fontSizes['display-md'], { lineHeight: '1.1', letterSpacing: '-0.02em' }],
				'display-sm': [tokens.typography.fontSizes['display-sm'], { lineHeight: '1.15', letterSpacing: '-0.02em' }],
			},
		},
	},
	plugins: [
		require('@tailwindcss/forms'),
		require('@tailwindcss/typography'),
	],
};
