<?php
//Begin Really Simple Security key
define('RSSSL_KEY', '2odg3HH9vO2iLjjFA9I8mW9Zjwf4j8EjfxvRm9SCLRT839y1wPLXozcSA7i74P8p');
//END Really Simple Security key

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';
require_once ABSPATH . 'wp-settings.php';
